name: Run Security Settings

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  run-security-settings:
    runs-on: ubuntu-latest
    environment:
      name: PROD

    steps:
    - name: Check out repository
      uses: actions/checkout@v4.2.2

    - name: Newman Action
      uses: matt-ball/newman-action@v2.0.0
      with:
        collection: configs/combined-features/security-settings.json
        environment: environments/prod/tsvi-solutions-env.json
        iterationData: environments/prod/repo_data.json
        reporters: '["cli","json"]'
        envVar: '[{"key": "GITHUB_TOKEN", "value": "${{ secrets.SECURITY_SETTINGS_TOKEN }}"}]'